### Gradle properties
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

### Mod Gradle properties
net.minecraftforge.gradle.merge-source-sets=true
fabric.loom.disableObfuscation=true
multiloader.enableAdvancedVersionSearch=true
multiloader.editPublishVersions=true

### Mod properties
mod.name=Message Display Time
mod.id=message_display_time
mod.version=1.2
mod.description=Adds a setting for the duration of displaying messages in the chat

### Publishing
mod.modrinth=XBxmgWxC
mod.curseforge=1327015
mod.github=message-display-time
