# Fabric versions see: https://fabricmc.net/develop
# Forge versions see: https://files.minecraftforge.net
# NeoForge versions see: https://neoforged.net
# Extra dependencies see: https://linkie.shedaniel.dev/dependencies

["1.16.5"]
pub_start="1.16"
pub_end="1.19.2"

["1.16.5-forge"]
pub_end="1.16.5"

["1.18"]
pub_end="1.18.2"

["1.19"]
pub_end="1.19.2"

["1.19.3"]
pub_end="1.19.4"

["1.20.1"]
pub_end="1.20.4"

["1.21.1"]
pub_start="1.20.5"
pub_end="1.21.10"

["1.21.1-forge"]
pub_start="1.20.6"

["26.1.2"]
pub_end="latest"
