### Mod properties
mod.name="Message Display Time"
mod.id="message_display_time"
mod.version="1.2"
mod.description="Adds a setting for the duration of displaying messages in the chat"

### Publishing
mod.modrinth="XBxmgWxC"
mod.curseforge="1327015"
mod.github="message-display-time"

### Subprojects
["26.2"]
pub-end="latest"

["1.21.1"]
pub-start="1.20.5"
pub-end="1.21.10"

["1.21.1-forge"]
pub-start="1.20.6"

["1.20.1"]
pub-end="1.20.4"

["1.19.3"]
pub-end="1.19.4"
